workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Build web app
        script: |
          cd frontend
          npm run build
      - name: Sync Capacitor
        script: |
          cd frontend
          npx cap sync ios
      - name: Pod Install
        script: |
          cd frontend/ios/App
          pod install
    artifacts:
      - frontend/ios/App/build/Release-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - user_email@example.com
