services:
  # Servicio para el Backend (Node.js)
  - type: web
    name: chatbots-backend
    env: node
    region: oregon
    plan: free
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: NODE_ENV
        value: production

  # Servicio para el Frontend (React)
  - type: static_site
    name: chatbots-frontend
    region: oregon
    plan: free
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    publishDir: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
